# color fix
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# General settings
set-option -g prefix C-b
bind-key C-b send-prefix
unbind C-h
set -g default-terminal "screen-256color" # terminal type
set -g aggressive-resize on               # aggressive resize
set -sg escape-time 0                     # escape time
set -g base-index 1                       # set initial window index to 1
set -g mouse on                           # enable mouse support
set -g bell-action none                   # disable bell
setw -g xterm-keys on                     # enable xterm keys
setw -g mode-keys vi                      # enable vi mode keys

# Better pane switching
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Vim stuff
bind C-a copy-mode
bind p run "xclip -o -sel clipboard"
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# Key bindings
bind | split-window -h -c "#{pane_current_path}" # split horizontally
bind - split-window -v -c "#{pane_current_path}" # split vertically
bind c new-window -c "#{pane_current_path}"      # open new window
bind x kill-pane                                 # kill pane without confirmation
bind w kill-window                               # kill window
bind q kill-session                              # kill session
bind r source-file ~/.tmux.conf                  # reload tmux config
bind t select-layout tiled                       # tiled layout
