CompileFlags:
  Add: [-xc, -Wall, -Wextra, -Werror, -Wno-self-assign, -Wshadow, -Wno-missing-field-initializers, -msse2, -mfsgsbase, -DSOL_DEF, -DDEBUG]
  Compiler: gcc

SemanticTokens:
  DisabledKinds: [InactiveCode]
